### ISSUE TITLE
Instructions not very clear

### ISSUE THREAD

**Issue by amol-modi** [Nishad94/UoP-Result-Data-Analayzer#2]
Nishad I can't exactly understand how to run the program. Can you tell me how I can see my rank. Anyways Amazing work!

Amol Modi

**Comment by Nishad94** [comment]
Assuming you are on Linux, clone this repository by creating a new directory and type : 
git clone https://github.com/Nishad94/UoP-Result-Data-Analayzer.git
python customFilter.py

**Comment by amol-modi** [comment]
Thanks! Very helpful
